### ISSUE TITLE
Some Video Files Are Not Playable After Conversion

### ISSUE THREAD

**Issue by Samuelodan** [softsingh/LyndaDecryptorUI#1]
First off, thanks so much for this invaluable tool. It's like a miracle.
So, I downloaded the latest version today and I noticed that after decrypting entire Lynda course folders, some of the videos are unplayable. And it seems I have established a pattern well. The affected courses are all courses that I had previously watched using the Lynda desktop app, while the unaffected courses ( the ones that have all their videos working) are courses that I have not watched or even viewed. 

So, please look into this. Thanks.

**Comment by softsingh** [comment]
Thank you very much for your words of appreciation. 
Most likely reason for videos not playing is that these may be partially downloaded. Delete the course and re download it. The Lynda Desktop app seems to be too buggy.
If possible share with me the link of the course or video folder and I will try it.

**Comment by Samuelodan** [comment]
Oh yeah, the Lynda Desktop app is so buggy, I hate it, ha ha.
Alright, thanks for responding. I'll try to redownload the videos.
I'll be sure to tell you how it goes. 

edit: Oh, I noticed that there are no subtitle files even in the original Lynda offline folders. Do you know a workaround for this?
I used to use some command prompt program to download the courses off Lynda's website, and it was able to get the subtitle files for each video.

**Comment by softsingh** [comment]
This happens to me also. I think, in some videos, subtitles are not included by Lynda.
